apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kodega2016/fib-api
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis-clusterip-svc

            - name: REDIS_PORT
              value: "6379"

            - name: POSTGRES_HOST
              value: postgres-clusterip-svc

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_DATABASE
              value: "postgres"

            - name: POSTGRES_USER
              value: "postgres"

            - name: POSTGRES_PASSWORD
              value: "supersecret"
