name: K8s Deployment
on:
  push:
    branches:
      - main
env:
  SHA: $(git rev-parse HEAD)

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: login to hub.docker.com
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build and run unit test
        run: |
          docker image build ./client -f ./client/Dockerfile.dev -t kodega2016/react-app-dev
          docker container run -e CI=true kodega2016/react-app-dev npm run test

  deployment:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: set google service keys for auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: set google cloud project
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{secrets.PROJECT_ID}}

      - name: use gcloud auth for docker
        run: gcloud --quiet auth configure-docker

      - name: get GKE credentials
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: ${{secrets.CLUSTER_NAME}}
          location: ${{secrets.CLUSTER_LOCATION}}
